/** @type {import('tailwindcss').Config} */
const semanticColor = (token) => `rgb(var(${token}) / <alpha-value>)`;

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: semanticColor("--color-background"),
        surface: semanticColor("--color-surface"),
        "surface-muted": semanticColor("--color-surface-muted"),
        "surface-glass": semanticColor("--color-surface-glass"),
        "surface-elevated": semanticColor("--color-surface-elevated"),
        "surface-floating": semanticColor("--color-surface-floating"),
        border: semanticColor("--color-border"),
        "border-muted": semanticColor("--color-border-muted"),
        "border-strong": semanticColor("--color-border-strong"),
        "border-glass": semanticColor("--color-border-glass"),
        "border-focus": semanticColor("--color-border-focus"),
        "border-error": semanticColor("--color-border-error"),
        "border-success": semanticColor("--color-border-success"),
        primary: semanticColor("--color-primary"),
        "primary-hover": semanticColor("--color-primary-hover"),
        "primary-active": semanticColor("--color-primary-active"),
        "on-primary": semanticColor("--color-on-primary"),
        secondary: semanticColor("--color-secondary"),
        info: semanticColor("--color-info"),
        success: semanticColor("--color-success"),
        warning: semanticColor("--color-warning"),
        danger: semanticColor("--color-danger"),
        "text-primary": semanticColor("--color-text-primary"),
        "text-secondary": semanticColor("--color-text-secondary"),
        "text-muted": semanticColor("--color-text-muted"),
        placeholder: semanticColor("--color-placeholder"),
        online: semanticColor("--color-online"),
        offline: semanticColor("--color-offline"),
        ai: semanticColor("--color-ai"),
        ghost: semanticColor("--color-ghost"),
        memory: semanticColor("--color-memory"),
        bookmark: semanticColor("--color-bookmark"),
        selection: semanticColor("--color-selection"),
        hover: semanticColor("--color-hover"),
        focus: semanticColor("--color-focus"),
        disabled: semanticColor("--color-disabled"),
        typing: semanticColor("--color-typing"),
        mention: semanticColor("--color-mention"),
        notification: semanticColor("--color-notification"),
        "on-surface": semanticColor("--color-text-primary"),
      },
      spacing: {
        0: "0px",
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        18: "4.5rem",
        22: "5.5rem",
      },
      borderRadius: {
        xs: "4px",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        floating: "var(--shadow-floating)",
        glass: "var(--shadow-glass)",
        xl: "var(--shadow-xl)",
        modal: "var(--shadow-modal)",
      },
      backdropBlur: {
        none: "0px",
        sm: "8px",
        glass: "var(--glass-blur)",
        dialog: "var(--glass-blur-dialog)",
        xl: "32px",
      },
      opacity: {
        glass: "var(--surface-opacity)",
        elevated: "var(--surface-elevated-opacity)",
        floating: "var(--surface-floating-opacity)",
        border: "var(--border-opacity)",
      },
      fontFamily: {
        sans: [
          "Inter",
          "SF Pro Display",
          "SF Pro Text",
          "system-ui",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "SFMono-Regular", "Fira Code", "monospace"],
      },
      fontSize: {
        meta: ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.01em" }],
        label: ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.005em" }],
        caption: [
          "0.8125rem",
          { lineHeight: "1.125rem", letterSpacing: "0.005em" },
        ],
        body: ["0.875rem", { lineHeight: "1.375rem" }],
        input: ["0.875rem", { lineHeight: "1.25rem" }],
        button: [
          "0.875rem",
          { lineHeight: "1.25rem", letterSpacing: "0.005em" },
        ],
        title: ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em" }],
        heading: [
          "1.25rem",
          { lineHeight: "1.75rem", letterSpacing: "-0.02em" },
        ],
        display: [
          "1.75rem",
          { lineHeight: "2.125rem", letterSpacing: "-0.03em" },
        ],
      },
      transitionDuration: {
        instant: "80ms",
        fast: "120ms",
        normal: "180ms",
        slow: "260ms",
        drawer: "320ms",
        modal: "220ms",
      },
      transitionTimingFunction: {
        premium: "cubic-bezier(0.2, 0, 0, 1)",
      },
      animation: {
        "fade-in": "fadeIn 160ms cubic-bezier(0.2, 0, 0, 1)",
        "slide-up": "fadeIn 160ms cubic-bezier(0.2, 0, 0, 1)",
        "scale-in": "fadeIn 140ms cubic-bezier(0.2, 0, 0, 1)",
        shimmer: "softPulse 1.8s ease-in-out infinite",
        typing: "softPulse 1.2s ease-in-out infinite",
        "ping-slow": "softPulse 2s ease-in-out infinite",
      },
      zIndex: {
        base: "0",
        dock: "20",
        sidebar: "30",
        header: "40",
        dropdown: "50",
        modal: "60",
        toast: "70",
      },
      width: {
        sidebar: "var(--sidebar-width)",
        "right-panel": "var(--right-panel-width)",
      },
      height: {
        "control-sm": "32px",
        control: "40px",
        "control-lg": "48px",
      },
      backgroundImage: {
        app: "var(--app-background)",
        dashboard: "var(--app-background)",
        auth: "var(--app-background)",
        light: "var(--app-background)",
        dark: "var(--app-background)",
        "landing-page": "var(--landing-page-bg)",
        "landing-hero": "var(--landing-hero-bg)",
        "landing-features": "var(--landing-features-bg)",
        "landing-ai": "var(--landing-ai-bg)",
        "landing-how": "var(--landing-how-bg)",
        "landing-light": "var(--landing-light-bg)",
        "landing-cta": "var(--landing-cta-bg)",
        "landing-footer": "var(--landing-footer-bg)",
      },
      minHeight: {
        "control-sm": "32px",
        control: "40px",
        "control-lg": "48px",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        softPulse: {
          "0%, 100%": { opacity: "0.45" },
          "50%": { opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
